meta_product_name: "Patrice - Portfolio"
meta_title: "Ici mon portfolio - Patrice Jaszczynski"
meta_description: "Besoin d'aide, d'un service, n'hésitez pas à me contacter"
meta_image: "patrice.jpeg" # should exist in `app/assets/images/`
