meta_product_name: "Patrice Jaszczynski- Portfolio"
meta_title: "Mon portfolio - Patrice Jaszczynski"
meta_description: "Patrice Jaszczynski - Data Analyste & Développeur Web - Besoin d'aide, d'un service, n'hésitez pas à me contacter"
meta_image: "profil.jpeg" # should exist in `app/assets/images/`
